version: '3'

services:
    app:
        image: node:16-alpine
        working_dir: /app
        volumes:
            - ./:/app
        env_file: ./.env
        ports:
            - 3000:3000
        command: ['yarn', 'dev']
